image: ruby:latest

before_script:
    - gem install dpl

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - staging

production:
    type: deploy
    stage: production
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - main